title: Rivers and Roads
author: Joswin
email: joswin@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Here is where we can learn about rivers and roads.  Here is a 
  description for you.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
